Spelling & Grammar Changes to index.html
ASEAN-Build-The-Earth/AseanBTE-Website pull request #96
Opened 2021-11-17 11:14 UTC by CrythicYT

Some Spelling and Phrasing Changes to the FAQ area.

2021-11-17 11:15 UTC, StoneMcYT commented
Related to :
https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/issues/95

2021-11-17 11:16 UTC, MatthewIsHereYT commented
Will update more tomorrow (18th Nov 2021)

2021-11-17 11:16 UTC, tintinkung commented
> Related to : #95

uh ya know ya can like an issue

2021-11-17 11:16 UTC, StoneMcYT commented
> 
> 
> Will update more tomorrow (18th Nov 2021)

kk will review when your done btw.

2021-11-17 11:32 UTC, Kira272921 commented
![image](https://user-images.githubusercontent.com/90365542/142192947-57a6a44e-2f11-420f-a6a8-df7ebe2b83a2.png)
 
 😕 Never heard this term in my entire life

2021-11-17 22:13 UTC, XboxBedrock commented
It’s a real term that refers to both north and South America

2021-11-18 02:18 UTC, Kira272921 commented
> It’s a real term that refers to both north and South America

Ah.. ok

2021-11-22 13:25 UTC, Kira272921 commented
> Will update more tomorrow (18th Nov 2021)

@MatthewIsHereYT You still working ?

2021-12-08 10:32 UTC, Kira272921 commented
@CrythicYT, Could you upload your avatar into [this](https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/tree/main/Assets/Images/avatars) directory ?

2021-12-08 10:33 UTC, Kira272921 commented on FAQ/index.html
> +                                    <p>You can watch <a class="link"href="https://www.youtube.com/watch?v=T174gWwD1MU">This Tutorial</a> on how to install the modpack. </p>
😅 Make `T` into lower case

2021-12-08 10:33 UTC, Kira272921 commented on FAQ/index.html
> +                                    <p>You can watch <a class="link"href="https://www.youtube.com/watch?v=T174gWwD1MU">This Tutorial</a> on how to install the modpack. </p>
😅 Make `T` into lower case

2021-12-08 10:34 UTC, Kira272921 requested changes
@CrythicYT, Here are few typography issue, rest of your work is great 👍

2021-12-22 09:25 UTC, StoneMcYT commented
This still active?

2021-12-22 10:12 UTC, tintinkung commented
I could fix and merge this

2021-12-22 10:20 UTC, tintinkung approved these changes
### good enough 👍

2021-12-22 10:22 UTC, merged