Added CrythicYT to the About Us Page + Spelling & Grammar
ASEAN-Build-The-Earth/AseanBTE-Website pull request #99
Opened 2021-12-08 10:32 UTC by CrythicYT

also changed Spelling and Wording of FAQ

2021-12-08 10:35 UTC, Kira272921 commented on About_Us/index.html
> +          I work rith Python and HTML and trying to learn others aswell.</p>
`rith` -> `with`

2021-12-08 10:35 UTC, Kira272921 requested changes
@CrythicYT Small typo

2021-12-08 11:23 UTC, CrythicYT commented
Small Typo Fixed

2021-12-08 11:24 UTC, Kira272921 approved these changes

2021-12-22 09:25 UTC, StoneMcYT commented
This still active?

2021-12-22 10:19 UTC, tintinkung commented
## 🔏  closed: duplicated from pr #96

2021-12-22 10:19 UTC, closed without merging